import type { Metadata } from "next";
import "./globals.css";
import AppSidebar from "@/features/sidebar/app-sidebar";
import { SidebarProvider } from "@/shared/components/ui/sidebar";
import Header from "@/features/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <div className="flex h-screen w-full">
            <AppSidebar />
            <div className="flex-1 flex flex-col min-w-0">
              <Header />
              <main className="flex-1 overflow-auto p-10">{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
